<?php

/**
 * GpolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GpolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GpolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gpol');
    }
}