<?php

/**
 * GroupUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    gpol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class GroupUser extends BaseGroupUser
{
	
	static function getGroupUserById($id){
		$groupuser = Doctrine_Core::getTable('GroupUser')
						->createQuery('a')
						->where( 'a.id = ?',$id)
						->execute();
		if(isset($groupuser[0]))
			return $groupuser[0];
		return false;
	}
	
	function addUser($userid){
		$grpUser = new LinkGroupUser();
		$grpUser->setUserId($userid);
		$grpUser->setGroupUserId($this->getId());
		$grpUser->save();
		return true;
	}


	function countUser(){
		$users = Doctrine_Core::getTable('LinkGroupUser')
						->createQuery('a')
						->where( 'a.group_user_id = ?',$this->getId())
						->execute();
		return count($users);
	}

	function getUsers(){
		$users = Doctrine_Core::getTable('User')
						->createQuery('a')
						->leftJoin('a.LinkGroupUser b')
						->where( 'b.group_user_id = ?',$this->getId())
						->execute();
		return $users;
	}

	function removeMembers(){
		$users = Doctrine_Core::getTable('LinkGroupUser')
								->createQuery('a')
								->delete()
								->where( 'a.group_user_id = ?',$this->getId())
								->execute();

	}
	
	function isMember(User $user){
		foreach($this->getUsers() as $muser){
			if($muser->getId() == $user->getId()){
				return true;
			}
		}
		return false;
	}
	
}
