<?php

/**
 * HostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Host');
    }
}