<?php

/**
 * Host
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gpol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Host extends BaseHost
{

	function __toString(){
		return $this->getName().' '.$this->getOs();
	}

	static function hostExist(Host $tmpHost)
	{
		$hosts = Doctrine_Core::getTable('host')
						->createQuery('a')
						->execute();

		foreach($hosts as  $host){
			if( $host->getSerial() == $tmpHost->getSerial()	)
				return true;
		}
		return false;
	}

	static function getHostBySerial($serial){
		$hosts = Doctrine_Core::getTable('host')
						->createQuery('a')
						->where('a.serial = ? ',$serial)
						->limit(1)
						->execute();

		if(isset($hosts[0]))
			return $hosts[0];
		else
			return false;
	}

	public function save(Doctrine_Connection $con = null)
  {
	  parent::save($con);
		$allHostGroup = GroupHost::getGroupHostById(-1);
    if(! $allHostGroup->isMember($this)){
	    $allHostGroup->addHost($this->getId());
    }
    return true;
  }

	function getGpols($typeid)
	{
		$gpols = Doctrine_Core::getTable('gpol')
						->createQuery('a')
						->leftJoin('a.LinkGpolHost b')
						->where( 'b.host_id = ?',$this->getId())
						->andWhere('a.type = ?',$typeid)
						->execute();

		$gpols2 = Doctrine_Core::getTable('gpol')
						->createQuery('a')
						->leftJoin('a.LinkGpolGroupHost b')
						->leftJoin('b.GroupHost c')
						->leftJoin('c.LinkGroupHost d')
						->where( 'd.host_id = ?',$this->getId())
						->andWhere('a.type = ?',$typeid)
						->execute();

		$gpols->merge($gpols2);
		return $gpols;
	}
}
