<?php

/**
 * LinkGroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGroupUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGroupUser');
    }
}