<?php

/**
 * LinkGpolHostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGpolHostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGpolHostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGpolHost');
    }
}