<?php

/**
 * LinkGpolGroupUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGpolGroupUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGpolGroupUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGpolGroupUser');
    }
}