<?php

/**
 * LinkGpolUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGpolUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGpolUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGpolUser');
    }
}