<?php

/**
 * LinkGpolGroupHostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGpolGroupHostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGpolGroupHostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGpolGroupHost');
    }
}