<?php

/**
 * LinkGroupHostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkGroupHostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkGroupHostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkGroupHost');
    }
}