<?php

/**
 * Log
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gpol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Log extends BaseLog
{
	static  $LEVEL_INFO = 1;
	static  $LEVEL_WARN = 2;
	static  $LEVEL_CRIT = 3;
	static $LEVEL_ARRAY = array(1=>'Info',2=>'Warn',3=>'Crit');

	static function getNameLevel($id){
		$tmp = Log::$LEVEL_ARRAY;
		return $tmp[$id];
	}

	static function addLog($action,$detail=false,$level=1){
		$log = new Log();
		$log->action = $action;
		$log->detail = $detail;
		$log->level = $level;
		$log->date = date(date('Y-m-d h:i:s'));
		$log->save();
	}

	static function addUserHostLog(User $user,Host $host,$action,$detail=false,$level=1){
		$log = new Log();
		$log->action = $action;
		$log->detail = $detail;
		$log->level = $level;
		$log->user_id = $user->getId();
		$log->host_id = $host->getId();
		$log->date = date(date('Y-m-d h:i:s'));
		$log->save();
	}

	static function addHostLog(Host $host,$action,$detail=false,$level=1){
		$log = new Log();
		$log->action = $action;
		$log->detail = $detail;
		$log->level = $level;
		$log->host_id = $host->getId();
		$log->date = date(date('Y-m-d h:i:s'));
		$log->save();
	}
}
