<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    gpol
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends BaseUser
{

	static function userExist(User $tmpUser)
	{
		$users = Doctrine_Core::getTable('user')
						->createQuery('a')
						->execute();

		foreach($users as  $user){
			if(
				$user->getName() == $tmpUser->getName()
			)
				return true;
		}
		return false;
	}

	function __toString(){
		$value= Config::getConfig('user_prefix');
		$tmp = substr($this->getName(),0,strlen($value));
		if($tmp == $value )
			return ''.substr($this->getName(),strlen($value));
		else
			return $this->getName();
	}


	function getGpols()
	{
		$gpols = Doctrine_Core::getTable('gpol')
						->createQuery('a')
						->leftJoin('a.LinkGpolUser b')
						->leftJoin('a.LinkGpolHost c')
						->where( 'b.user_id = ?',$this->getId())
						->andWhere('a.type != ?',"1") //différent de boot
						->execute();

		$gpols2 = Doctrine_Core::getTable('gpol')
						->createQuery('a')
						->leftJoin('a.LinkGpolGroupUser b')
						->leftJoin('b.GroupUser c')
						->leftJoin('c.LinkGroupUser d')
						->where( 'd.user_id = ?',$this->getId())
						->AndWhere('a.type != ?',"1") //différent de boot
						->execute();

		$gpols->merge($gpols2);


		return $gpols;
	}

	
	public function save(Doctrine_Connection $con = null)
  {
	  parent::save($con);
		$allUserGroup = GroupUser::getGroupUserById(-1);
    if(! $allUserGroup->isMember($this)){
	    $allUserGroup->addUser($this->getId());
    }
    return true;
  }
}
